### ISSUE TITLE
Paušální grant pro Brněnské PyLadies

### ISSUE THREAD

**Issue by encukou** [pyvec/money#1]
<small>*(Pro vyzkoušení systému a vytvoření příkladu pro ostatní sem kopíruju už odsouhlasený grant.)*</small>

**Kdo jste?**
Brněnské PyLadies

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**
max. 100 Kč měsíčně

**Na jakou věc to je?**
* Kancelářské potřeby (lepící papírky, jmenovky)
* Drobné ceny do soutěže (typicky je soutěž jednou za kurz, první tři dostanou čokoládu)

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Brněnské PyLadies dělají kurzy pro začátečníky i pokročilejší: několik kurzů každý semestr (viz https://pyladies.cz/brno/) plus jednorázovky (https://pyworking.cz/).

**Comment by honzajavorek** [comment]
Nakonec nám to tady vyzkoušely @ivafingerova a @radusaaa s reálnými novými granty, tak přemýšlím, jestli toto nějak nesmazat.
