### ISSUE TITLE
Trička pro PyLadies

### ISSUE THREAD

**Issue by Zuzanita** [pyvec/money#10]
**Kdo jste?**
Organizátoři PyLadies - podává Zuzana Pokorná za všechny 

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**
25 000 Kč z toho bude část vrácena z příspěvků jednotlivců na trička

**Na jakou věc to je?**
Trička PyLadies pro účastnice/účastníky, koučky/koučky a organizátorky/organizátory

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Propagace PyLadies a jejich kurzů, radost všech výše uvedených

**Comment by honzajavorek** [comment]
Díky, na nejbližší schůzi odhlasujeme!

**Comment by baradrb** [comment]
Schváleno!
Poznámka: příště napište počet kusů, kolik se bude vyrábět, díky.

**Comment by honzajavorek** [comment]
@Zuzanita Budeme se těšit na článek na https://blog.python.cz/ ❤️ (klidně krátký!)
