### ISSUE TITLE
Vytvoření faktury pro Heureka Group na sponzoring meetupu PyData Prague #14

### ISSUE THREAD

**Issue by kreneka** [pyvec/money#11]
**Kdo jste?**
Adam Křenek - PyData Prague org team

**Na jakou věc to je?**
Partnerství meetupu PyData Prague #14 a Heureka Group

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Z peněz za partnerství zaplatíme zahraničního speakera - letenka a ubytko

**Částka**
10.000 czk

**Fakturační údaje protistrany**
Heureka Group a.s.

Karolinská 706/3
186 00  Praha 8 - Karlín
Česká republika

B 24131 vedená u Městského soudu v Praze
IČ: 07822774 DIČ: CZ07822774

Bankovní účet UniCredit Bank: 2110986041/2700
IBAN kód: CZ28 2700 0000 0021 1098 6041
SWIFT: BACXCZPP

**E-mail protistrany**
michal.rychlik@heureka.cz

**Je potřeba podepsat nějakou smlouvu? (sponzorskou, nájemní…)**
ne

---

_Otočení sponzorských peněz nepodléhá schvalování výborem._
_Žádost přímo zpracuje predseda nebo pokladník spolku._

**Comment by sairon** [comment]
Záležitost už je nějakou chvíli vyřešená, issue tedy zavírám.
