### ISSUE TITLE
Jednorázový grant na výrobu samolepek PyLadies

### ISSUE THREAD

**Issue by befeleme** [pyvec/money#12]
**Kdo jste?**
Karolina Surma - PyLadies

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**
~6800 Kč 

*detailně*
hlavička: 6.24 Kč / ks = 2496 Kč
logo: 6.78 Kč / ks = 2712 Kč
+ DPH (21%) + (doprava 350 Kč + DPH)

**Na jakou věc to je?**
Výroba samolepek PyLadies: hlavička ve 4 barvách, logo ve 4 barvách, od každé kombinace 100 ks.

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Pro propagační účely: Letos máme v ČR dvě konference: EuroPython a PyCon CZ + při propagaci lokálních eventů. Do offline se vrácí i další programátorské eventy, nejen čistě Pythonní.
Jen letos v Brně jsme uspořádaly 6 workshopů a 2 dlouhodobé kurzy. Samolepky budou k dispozici všem PyLadies z Republiky, které o ně požádají.

**Comment by honzajavorek** [comment]
Grant jsme schválili! 🎉 Vyřeší to s tebou @sairon 💰

**Comment by honzajavorek** [comment]
@befeleme Mělo by to být poslané, zavírám.

**Comment by honzajavorek** [comment]
@befeleme Budeme se těšit na článek na https://blog.python.cz/ ❤️ (klidně krátký!)
