### ISSUE TITLE
Jednorázový grant na PyCon CZ trička na EuroPython

### ISSUE THREAD

**Issue by clytaemnestra** [pyvec/money#13]
**Kdo jste?**
PyCon CZ

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**
2990

**Na jakou věc to je?**
trička na EuroPython pro stankaře 

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
promoce PyCon CZ a české komunity

**Comment by clytaemnestra** [comment]
[tisknitextil.cz_invoice_20230168.pdf](https://github.com/pyvec/money/files/12164359/tisknitextil.cz_invoice_20230168.pdf)

**Comment by honzajavorek** [comment]
Grant jsme schválili! 🎉 Vyřeší to s tebou @sairon 💰

**Comment by honzajavorek** [comment]
Tak prý to zrovna i poslala, zavírám 💸

**Comment by baradrb** [comment]
Money sent.

**Comment by honzajavorek** [comment]
@clytaemnestra Budeme se těšit na článek na https://blog.python.cz/ ❤️ (klidně krátký!)
