### ISSUE TITLE
Jednorázový grant na dort na Pyvo

### ISSUE THREAD

**Issue by clytaemnestra** [pyvec/money#15]
**Kdo jste?**
pražské Pyvo

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**
2080

**Na jakou věc to je?**
dort

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
na kulaté narozeniny Pyva

Článek bude, až posbírám fotky.

**Comment by clytaemnestra** [comment]
[Invoice.pdf](https://github.com/pyvec/money/files/13466658/Invoice.pdf)

**Comment by baradrb** [comment]
@clytaemnestra nějak nenacházím číslo účtu, kam ti to mám poslat...

**Comment by baradrb** [comment]
Okay, posláno na Miin účet.
