### ISSUE TITLE
Otočení sponzorských peněz

### ISSUE THREAD

**Issue by clytaemnestra** [pyvec/money#17]
**Kdo jste?**
Python Pizza

**Na jakou věc to je?**
Python Pizza

**Částka**
20k

**Fakturační údaje protistrany**
stejné jako tady https://app.fakturoid.cz/pyvec/p/EYVp8l8UPA/2023018

**E-mail protistrany**
klidně do vlákna, pak to stáhnu

**Je potřeba podepsat nějakou smlouvu? (sponzorskou, nájemní…)**
ne

---

_Otočení sponzorských peněz nepodléhá schvalování výborem._
_Žádost přímo zpracuje predseda nebo pokladník spolku._

**Comment by baradrb** [comment]
https://app.fakturoid.cz/pyvec/p/10hpqux8Og/2023020
