### ISSUE TITLE
Proplacení meetup.com pro Pyvo Praha

### ISSUE THREAD

**Issue by benabraham** [pyvec/money#18]
**Kdo jste?**
Daniel Srb

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**
1291.82 Kč
Účty jsou v dolarech, ale tohle mi odešlo z banky.

**Na jakou věc to je?**
Proplacení Meetup.com pro Pyvo Praha za 3 měsíce, kdy jsem to platil ze svého.

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Nepřišli jsme o Meetup.

**Comment by benabraham** [comment]
A asi by bylo dobré napsat číslo účtu 1029585019/3030.

**Comment by honzajavorek** [comment]
Omlouváme se, že na to koukáme až teď. Nějak se nám nedařilo teď potkat a tím se to strašně protáhlo 😞 Pošli nám prosím z toho Meetupu jestli máš nějaký daňový doklad nebo účtenku, sem nebo na info@pyvec.org, a proplatíme.

**Comment by benabraham** [comment]
Posláno.
