### ISSUE TITLE
Python Community Sprint na Východě 2024

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/money#19]
**Kdo jste?**

Lumír Balhar, člen Pyvce, organizátor Pyva v Ostravě

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**

10 000 Kč - odhad na jídlo a pití pro 12 lidí na tři dny.

**Na jakou věc to je?**

Jarni edice komunitního sprintu 26. - 28. dubna 2024.

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**

Organizujeme tradiční víkendový sraz pro všechny organizátory a organizátorky Python akcí v České Python komunitě. Plánují se aktivity, které budou (pycon.cz/pyladies/pyva), dokumentují se ty, které byly (pycon.cz/pyladies/pyva), sepisuje se různá dokumentace (naucse/odevzdavatko/python.cz), zpracovávají se issues (zapojse/pyvec/money) a zkrátka se sprintuje na všech možných ůkolech, na které se během roku nenajde čas.

**Comment by frenzymadness** [comment]
Finální účet:

* Nákup ve čtvrtek: 1151 Kč
* Sobotní oběd: 2016 Kč
* Nákup v sobotu: 2117 Kč

Celkem tedy 5284 Kč

A k tomu dotaz. Za nákupy účtenky mám, ale objednané jídlo dorazilo bez nich (ze dvou různých míst). Reklamoval jsem to u Foodory a oni se účtenky pokusí získat od restaurace, ale může to trvat i týdny. Nedalo by se to vyřešit screeny z aplikace s nějakým čestným prohlášením nebo tak? Vím, že Kubík vystavuje faktury, ale tuhle možnost já nemám, bohužel.

**Comment by honzajavorek** [comment]
@baradrb se zeptá účetního

**Comment by baradrb** [comment]
@frenzymadness prosím nahraj fotky účtenek do https://drive.google.com/drive/folders/1-f2QGvVjv71KPEcLRbKiW_2NqIRFPhUU, ohledně účtenek z foodory chvíli počkejme, jestli něco dodají, jinak vyřešíme přes Dana, který se nabídl, že na tu částku může vystavit fakturu.

**Comment by frenzymadness** [comment]
Fotografie účtenek z Kauflandu je na disku.

**Comment by frenzymadness** [comment]
Nevím, jestli jsem už předtím posíla číslo účtu, tak tady je: 5748802399/0800

Dan už mi proplatil finance z faktury, takže zbývá proplatit účtenky z Kauflandu. Můžu to nějak posunout kupředu?

**Comment by baradrb** [comment]
Podle účtenek proplácím 3269,41 Kč.
