### ISSUE TITLE
Meetup.com subscription fee pr PyWorking

### ISSUE THREAD

**Issue by IvaFingerova** [pyvec/money#2]
**Kdo jste?**
Iva Fingerová

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**
1 723,- CZK

**Na jakou věc to je?**
Subscription meetup.com pro Pyworking

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Pomáháme PyLadies v pokračování po kurzu, šíříme Pythoní dobro :)

Tu je výpis z účtu:
[Meetup_platby.pdf](https://github.com/pyvec/money/files/4197644/Meetup_platby.pdf)

**Comment by kvbik** [comment]
Kdyby se nekdy nekomu chtelo ty meetupy vsechny hodit do jednoho, to by se mi moc libilo. Pyva, Pyworkings a spol. ale vim, ze uz jsme to parkrat resili :D Jinak samozrejme proplaceni za me samozrejme 👍

**Comment by encukou** [comment]
Jednorázově (za jaké období), nebo to bude potřeba i do budoucna?

**Comment by IvaFingerova** [comment]
Je to půlroční fee - strhává se mi automaticky z karty

**Comment by IvaFingerova** [comment]
Další platb a proběhne:
Your last payment of US$36.23 was received on Oct 10, 2019.
Your next payment of $29.94 (plus tax) for a Meetup Subscription: 6 months plan will be charged on **Apr 10, 2020.**
Do té doby se zavazuji promyslet přípravu jednoho účtu na Pyvec.org a jestlii tam půjde mít společné meetupy - pak bychom to mergli a tadá! 
Souhlas? @kvbik @encukou 

Jde nám o eventy:
Pyvo - praha, ale dává smysl tam přidat i Brněnské/Plzeňské/... Pyvo, že? 
Pražský Pyworking
Máme ještě nějaké eventi?

Dík! Muck!
I

**Comment by honzajavorek** [comment]
Brněnské Pyvo myslím taky mělo nějaký účet na meetupu. Nevím, jestli to půjde dát pod jeden, myslím, že jsme to nějak zkoušeli dřív, ale nebylo to snadno proveditelné. Taky by tím vznikl účet, kde se přihlašuje hodně různých lidí z celé republiky, a kde je zároveň uložená nějaká kreditní karta. Možná nakonec lepší, když si to každá skupina řeší sama a my budem jen proplácet?

Toto je tedy grant na 1 723,- CZK / půlrok, tzn. **[paušální grant](https://docs.pyvec.org/operations/support-money.html#pausalni-granty) na 300 Kč měsíčně, dlouhodobě**.

**Comment by honzajavorek** [comment]
(Příští týden máme mít schůzi rady, tak to asi dohlasujem na ní.)

**Comment by encukou** [comment]
Meetup účet pro Brněnské Pyvo platí myslím přímo Kiwi.com.

**Comment by IvaFingerova** [comment]
> Meetup účet pro Brněnské Pyvo platí myslím přímo Kiwi.com.

a koná se to na Kiwi půdě, nebo to je dlouhodobý sponzoring?

**Comment by kvbik** [comment]
Mozna inspirace jsou ty meetup.com PRO ucty. Jako to maji prazske PyData [1], ty jsou samostana group, ale placene jsou pres ten hlavni ucet [2].

[1] https://www.meetup.com/PyData-Prague/
[2] https://www.meetup.com/pro/pydata/

**Comment by encukou** [comment]
> a koná se to na Kiwi půdě, nebo to je dlouhodobý sponzoring?

Jen dlouhodobý sponzoring.

**Comment by kvbik** [comment]
BTW, uz jsme to mozna resili driv, ale na meetup.com je moznost mit organizaci ala pydata [1] a pak ty jednotlive "groups" mit pod timto uctem, opet ala prague pydata [2]. Je to ovsem zrejme o dost drazsi. Jestli dobre koukam na pricing, tak je to $30 per group per month... Coz je trosku ulet, kdyz jednotlivy organizator to muze mit za $10.

[1] https://www.meetup.com/pro/pydata/
[2] https://www.meetup.com/PyData-Prague/

**Comment by honzajavorek** [comment]
Dnes schváleno! Dále prosím postupuj podle [návodu zde](https://docs.pyvec.org/operations/runbooks.html#jak-si-nechat-neco-proplatit) 💸 

S diskusí o tom, jak bychom mohli platit meetup.com v budoucnu pro všechny aktivity Pyvce se prosím přesuňte na https://github.com/pyvec/zapojse/issues
