### ISSUE TITLE
Proplaceni obcerstveni pro PyData Prague Meetup c. 20 na FJFI

### ISSUE THREAD

**Issue by sarimak** [pyvec/money#20]
**Kdo jste?**
Jirka Bajer

**Na jakou věc to je?**
PyData Prague Meetup c. 20 na FJFI (OSSCi)

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Obcerstveni pro meetup ktery se kona na neziskove venue => obcerstveni neni sponzorovane.
(obcerstveni kupujeme navickrat, tohle je prvni a nejspis i nejvetsi platba)

**Částka**
6560 Kc

**Fakturační údaje protistrany**
Uctenka z pokladny, prilozena k Slack threadu https://pyvec.slack.com/archives/C9E81JFS5/p1715435147908279
Cislo meho uctu tamtez.

**E-mail protistrany**
N/A

**Je potřeba podepsat nějakou smlouvu? (sponzorskou, nájemní…)**
Ne

---

_Otočení sponzorských peněz nepodléhá schvalování výborem._
_Žádost přímo zpracuje predseda nebo pokladník spolku._

**Comment by baradrb** [comment]
Vyřízeno.
