### ISSUE TITLE
Proplacení nápojů pro PyData Prague Meetup č. 20 na FJFI

### ISSUE THREAD

**Issue by coobas** [pyvec/money#21]
**Kdo jste?**
Jakub Urban

**Na jakou věc to je?**
PyData Prague Meetup č. 20 na FJFI (OSSCi)

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Nápoje pro meetup který se koná na neziskové venue => občerstveni není sponzorované.
(občerstvení kupujeme navíckrat, tohle je druhá část - hlavně nápoje)

**Částka**
4 436,25

**Fakturační údaje protistrany**
Prosím proplatit na účet 324150961 / 0300
[makro-pydata-meetup.pdf](https://github.com/pyvec/money/files/15316764/makro-pydata-meetup.pdf)

**E-mail protistrany**
jakub.urban@pydata.cz

**Je potřeba podepsat nějakou smlouvu? (sponzorskou, nájemní…)**
ne

---

_Otočení sponzorských peněz nepodléhá schvalování výborem._
_Žádost přímo zpracuje predseda nebo pokladník spolku._

**Comment by baradrb** [comment]
Peníze odeslány.
