### ISSUE TITLE
Proplacení cestovného + ubytování speakera na PyData Prague meetup #20

### ISSUE THREAD

**Issue by coobas** [pyvec/money#22]
**Kdo jste?**
Jakub Urban

**Na jakou věc to je?**
Cestovní výdaje speakera na PyData Prague Meetup č. 20 na FJFI (OSSCi)

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Derek Homeier byl pozván aby mluvil o Astropy, proplácíme mu cestovné a jednu noc ubytování.

**Částka**
256.01 EUR
(vlak + jedna noc v hotelu)
[DB_Ticket_549617778315.pdf](https://github.com/pyvec/money/files/15429901/DB_Ticket_549617778315.pdf)
[DB_Ticket_925747902973.pdf](https://github.com/pyvec/money/files/15429905/DB_Ticket_925747902973.pdf)
[SwiftScan-Golden_City-20240515.pdf.pdf](https://github.com/pyvec/money/files/15429907/SwiftScan-Golden_City-20240515.pdf.pdf)

**Fakturační údaje protistrany**
Prosím poslat na:
Derek Homeier
IBAN: DE46 4306 0967 1182 4814 00
BIC: GENODEM1GLS

**E-mail protistrany**
dhomeie@gwdg.de

**Je potřeba podepsat nějakou smlouvu? (sponzorskou, nájemní…)**
ne

---

_Otočení sponzorských peněz nepodléhá schvalování výborem._
_Žádost přímo zpracuje predseda nebo pokladník spolku._

**Comment by baradrb** [comment]
Vyřízeno.
