### ISSUE TITLE
Faktura pro PyData Prague Meetup -- Keboola

### ISSUE THREAD

**Issue by jiri-bajer** [pyvec/money#23]
**Kdo jste?**
Jirka Bajer, PyData Prague Meetup org

**Na jakou věc to je?**
Cervnovy PyData Prague Meetup v Keboole

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Sponzorsky prispevek od Kebooly

**Částka**
10 000,- Kc

**Fakturační údaje protistrany**
Keboola Czech s.r.o.
Dělnická 191/27, Holešovice, 170 00 Prague 7, Czech Republic
ICO: 28502787
DIC: CZ28502787

**E-mail protistrany**
Prosim o poslani odkazu na fakturu ve Fakturoidu do Slack kanalu #money

**Je potřeba podepsat nějakou smlouvu?**
Ne

**Comment by baradrb** [comment]
Odkaz poslán na slack.
