### ISSUE TITLE
Grant pro pražské PyLadies - jarní běh 2020

### ISSUE THREAD

**Issue by radusaaa** [pyvec/money#3]
**Kdo jste?**
PyLadies Praha

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**
500,- Kč za oba běhy 

**Na jakou věc to je?**

- kancelářské potřeby

- drobné odměny do soutěží 

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
Organizujeme dva běhy začátečnických kurzů viz https://pyladies.cz/praha/. Součástí kurzů jsou i dva sobotní celodenní pyworkingy a závěrečný hackathon.

**Comment by honzajavorek** [comment]
Dnes schváleno! Dále prosím postupuj podle [návodu zde](https://docs.pyvec.org/operations/runbooks.html#jak-si-nechat-neco-proplatit) 💸
