### ISSUE TITLE
PyData listopad 2019 - náklady zahraničního speakera

### ISSUE THREAD

**Issue by janpipek** [pyvec/money#5]
**Kdo jste?**

Jan Pipek (za PyData Prague)

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**

5 587,09 Kč

**Na jakou věc to je?**

Náklady zahraničního speakera na meetupu (ubytování + cestovné), Dom Weldon.

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**

Původně se mělo jednat o jednoduché otočení sponzorských peněz (PyVec 19.12.2019 proplatil) ale po několikaměsíční prokrastinaci (nejdříve frmol na konci roku, pak vnitrofiremní problémy, pak covid, pak ... v zásadě už jen prokrastinace) ze sponzorské firmy odešel původní jednatel, nadšený podporovatel, a slíbenou částku se mi už nepodařilo vydobýt. Po dohodě s @martinbilek  tedy žádám o zpětné překategorizování jako jednorázový grant.

Obecně PyData meetupy snad jsou dobrý nápad a tohle byl zatím nejúspěšnější talk, alespoň podle počtu shlédnutí záznamu na Youtube (>6k): https://www.youtube.com/watch?v=dewrzMPPLDU .

**Comment by honzajavorek** [comment]
Ahoj, super, schváleno! Běžně standardní granty [podmiňujeme](https://docs.pyvec.org/operations/support-money.html#granty) článkem na [blog](https://blog.python.cz/), ale protože jde v tomto případě o speciální situaci, tak tím udělení grantu nechceme podmiňovat. Samozřejmě, kdybys chtěl něco na blog o PyData a třeba i o té konkrétní přednášce a úspěchu, jaký to mělo, napsat, bylo by to super 🙂 Hlasování zavírám.
