### ISSUE TITLE
Pražské Pyvo - pronájem projektoru a audiotechniky

### ISSUE THREAD

**Issue by clytaemnestra** [pyvec/money#9]
**Kdo jste?**
spoluorganizátorka pražského Pyva

**Kolik potřebujete? (aspoň odhad nebo rozmezí)**
726 Kč

**Na jakou věc to je?**
pronájem projektoru + audiotechniky

**Proč? (čemu prospějeme, proč je to dobrý nápad, jaký to bude mít dopad?)**
na přednášky a lightning talky

**Comment by honzajavorek** [comment]
Díky Mio, grant odhlasujeme nejpozději 1.12., kdy máme schůzi výboru 👍

**Comment by honzajavorek** [comment]
Díky Mio, grant odhlasujeme nejpozději 1.12., kdy máme schůzi výboru 👍

**Comment by honzajavorek** [comment]
Grant jsme schválili! 🎉 Vyřeší to s tebou @sairon 💰

**Comment by sairon** [comment]
Proplaceno.

**Comment by honzajavorek** [comment]
@clytaemnestra Budeme se těšit na článek na https://blog.python.cz/ ❤️ (klidně krátký!)
